CREATE TABLE faqa(
    NO NUMBER PRIMARY KEY,
    TITLE VARCHAR2(100) NOT NULL,
    CONTENT VARCHAR2(600),
    AUTHOR VARCHAR2(16),
    RESDATE DATE DEFAULT SYSDATE,
    GUBUN NUMBER NOT NULL,      -- 질문(0)/답변(1) 구분
    PARNO NUMBER NOT NULL       -- 질문(1)과 답변(1)의 공통 번호
    );    
    
    
SELECT * FROM FAQA ORDER BY PARNO ASC, GUBUN ASC;

CREATE SEQUENCE F_SEQ;


COMMIT;

-- 질문
INSERT INTO FAQA VALUES(F_SEQ.NEXTVAL, '질문1', '내용1', 'admin', SYSDATE, 0, F_SEQ.CURRVAL);
INSERT INTO FAQA VALUES(F_SEQ.NEXTVAL, '질문2', '내용2', 'admin', SYSDATE, 0, F_SEQ.CURRVAL);
INSERT INTO FAQA VALUES(F_SEQ.NEXTVAL, '질문3', '내용3', 'admin', SYSDATE, 0, F_SEQ.CURRVAL);
INSERT INTO FAQA VALUES(F_SEQ.NEXTVAL, '질문4', '내용4', 'admin', SYSDATE, 0, F_SEQ.CURRVAL);
INSERT INTO FAQA VALUES(F_SEQ.NEXTVAL, '질문5', '내용5', 'admin', SYSDATE, 0, F_SEQ.CURRVAL);
-- 답변
INSERT INTO FAQA VALUES(F_SEQ.NEXTVAL, '질문1에 대한 답변', '답변내용1', 'admin', SYSDATE, 1, 1);
INSERT INTO FAQA VALUES(F_SEQ.NEXTVAL, '질문2에 대한 답변', '답변내용2', 'admin', SYSDATE, 2, 2);




