/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.23
 * Generated at: 2022-10-28 04:13:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class custom_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/nav.jsp", Long.valueOf(1666920147621L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>업비트 - 가장 신뢰받는 디지털 자산 거래소</title>\r\n");
      out.write("    <!-- 메타포(검색엔진에서 잘 검색되기 위해서) -->\r\n");
      out.write("    <meta property=\"og:url\" content=\"/home\">\r\n");
      out.write("    <meta property=\"og:site_name\" content=\"업비트 - 가장 신뢰받는 디지털 자산 거래소\">\r\n");
      out.write("    <meta property=\"og:title\" content=\"업비트\">\r\n");
      out.write("    <meta property=\"og:image\" content=\"https://static.upbit.com/upbit-pc/seo/upbit_facebook.png\">\r\n");
      out.write("    <meta property=\"og:image:width\" content=\"800\">\r\n");
      out.write("    <meta property=\"og:image:height\" content=\"400\">\r\n");
      out.write("    <meta property=\"og:description\" content=\"디지털 자산, 비트코인, 이더리움, 리플, 에이다, 솔라나 등 알트코인 거래.\">\r\n");
      out.write("    <meta property=\"og:locale\" content=\"ko_kr\">\r\n");
      out.write("    <meta property=\"og:type\" content=\"website\">\r\n");
      out.write("    <meta name=\"twitter:card\" content=\"summary\">\r\n");
      out.write("    <meta name=\"twitter:url\" content=\"/home\">\r\n");
      out.write("    <meta name=\"twitter:site_name\" content=\"업비트 - 가장 신뢰받는 디지털 자산 거래소\">\r\n");
      out.write("    <meta name=\"twitter:title\" content=업비트>\r\n");
      out.write("    <meta name=\"twitter:image\" content=\"https://static.upbit.com/upbit-pc/seo/upbit_facebook.png\">\r\n");
      out.write("    <meta name=\"twitter:image:width\" content=\"1200\">\r\n");
      out.write("    <meta name=\"twitter:image:height\" content=\"627\">\r\n");
      out.write("    <meta name=\"twitter:description\" content=\"디지털 자산, 비트코인, 이더리움, 리플, 에이다, 솔라나 등 알트코인 거래.\">\r\n");
      out.write("    <meta name=\"twitter:locale\" content=ko_kr>\r\n");
      out.write("    <meta name=\"twitter:type\" content=\"website\">\r\n");
      out.write("    <meta name=\"author\" content=두나무>\r\n");
      out.write("    <meta name=\"image\" content=\"https://static.upbit.com/upbit-pc/seo/upbit_facebook.png\">\r\n");
      out.write("    <!--파비콘-->\r\n");
      out.write("    <link rel=\"shortcut icon\" href=\"./pic/favicon.jpg\">\r\n");
      out.write("    <!--각종 플러그인과 설정 파일-->\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Nanum+Gothic&family=Noto+Sans+KR&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    <!-- 구형 브라우저 html5태그 인식 -->\r\n");
      out.write("    <script src=\"./js/html5shiv.js\"></script>\r\n");
      out.write("    <!-- 구형 브라우저에서 css animation 인식 -->\r\n");
      out.write("    <script src=\"./js/prefixfree.min.js\"></script>\r\n");
      out.write("    <!-- 구형 브라우저에서 미디어쿼리 인식 -->\r\n");
      out.write("    <script src=\"./js/respond.min.js\"></script>\r\n");
      out.write("    <!-- jquery 플러그인 연결 -->\r\n");
      out.write("    <script src=\"./js/jquery-1.11.1.js\"></script>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./css/reset2.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"header.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"footer.css\">\r\n");
      out.write("    <style>\r\n");
      out.write("        /* header.css */\r\n");
      out.write("        .hd {\r\n");
      out.write("            position: fixed;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* content */\r\n");
      out.write("        .vs {\r\n");
      out.write("            clear: both;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 300px;\r\n");
      out.write("            overflow: hidden;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .vs img {\r\n");
      out.write("            display: block;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: auto;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .bread {\r\n");
      out.write("            clear: both;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            line-height: 60px;\r\n");
      out.write("            border-bottom: 3px solid rgb(129, 175, 219);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .bread_fr {\r\n");
      out.write("            width: 1200px;\r\n");
      out.write("            margin: 0 auto;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .page {\r\n");
      out.write("            clear: both;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            min-height: 100vh;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .page:after {\r\n");
      out.write("            content: \"\";\r\n");
      out.write("            display: block;\r\n");
      out.write("            clear: both;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .page_wrap {\r\n");
      out.write("            width: 1200px;\r\n");
      out.write("            margin: 0 auto;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .content {\r\n");
      out.write("            display: none;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .content:target {\r\n");
      out.write("            display: block;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .page_wrap {\r\n");
      out.write("            padding: 2em;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .page_title {\r\n");
      out.write("            padding-top: 1em;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .home {\r\n");
      out.write("            color: rgb(0, 0, 0);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .noti_lst {\r\n");
      out.write("            display: block;\r\n");
      out.write("            margin: 80px auto;\r\n");
      out.write("            width: 1000px;\r\n");
      out.write("            height: 800px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .noti_lst li {\r\n");
      out.write("            clear: both;\r\n");
      out.write("            height: 55px;\r\n");
      out.write("            line-height: 32px;\r\n");
      out.write("            border-bottom: 2px solid rgb(157, 175, 212);\r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .noti_lst li:first-child {\r\n");
      out.write("            border-top: 3px solid #333;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .noti_lst li span {\r\n");
      out.write("            display: block;\r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("            float: left;\r\n");
      out.write("            line-height: 50px;\r\n");
      out.write("            font-size: 20px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .noti_num {\r\n");
      out.write("            width: 80px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .noti_tit {\r\n");
      out.write("            width: 700px;\r\n");
      out.write("            overflow: hidden;\r\n");
      out.write("            text-overflow: ellipsis;\r\n");
      out.write("            white-space: nowrap;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .item_hd {\r\n");
      out.write("            font-weight: 700;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .noti_tit.item_hd {\r\n");
      out.write("            text-align: center;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .noti_tit a {\r\n");
      out.write("            display: block;\r\n");
      out.write("            overflow: hidden;\r\n");
      out.write("            text-overflow: ellipsis;\r\n");
      out.write("            white-space: nowrap;\r\n");
      out.write("            padding-right: 12px;\r\n");
      out.write("            color: #333;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .noti_auth {\r\n");
      out.write("            width: 100px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .noti_date {\r\n");
      out.write("            width: 120px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .to_top {\r\n");
      out.write("            position: fixed;\r\n");
      out.write("            bottom: 80px;\r\n");
      out.write("            right: 80px;\r\n");
      out.write("            z-index: 999;\r\n");
      out.write("            background-color: rgb(211, 153, 44);\r\n");
      out.write("            color: black;\r\n");
      out.write("            display: block;\r\n");
      out.write("            width: 60px;\r\n");
      out.write("            height: 60px;\r\n");
      out.write("            line-height: 60px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            font-size: 20px;\r\n");
      out.write("            border-radius: 32px;\r\n");
      out.write("            visibility: hidden;\r\n");
      out.write("            transition-duration: 0.8s;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .to_top:hover {\r\n");
      out.write("            background-color: aqua;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .to_top.on {\r\n");
      out.write("            visibility: visible;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"footer.css\">\r\n");
      out.write("    <script>\r\n");
      out.write("        $(document), ready(function () {\r\n");
      out.write("            $(window).scroll(function () {\r\n");
      out.write("                var ht = $(window).height();\r\n");
      out.write("                var tp = $(this).scrollTop();\r\n");
      out.write("                if (tp >= 300) {\r\n");
      out.write("                    $(\".to_top\").addClass(\"on\");\r\n");
      out.write("                    $(\".to_top\").attr(\"href\", location.href);\r\n");
      out.write("                } else {\r\n");
      out.write("                    $(\".to_top\").removeClass(\"on\");\r\n");
      out.write("                    $(\".to_top\").attr(\"href\", location.href);\r\n");
      out.write("                }\r\n");
      out.write("            });\r\n");
      out.write("        });\r\n");
      out.write("    </script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"wrap\">\r\n");
      out.write("        <header class=\"hd\">\r\n");
      out.write("            ");
      out.write('\r');
      out.write('\n');

	String name = (String) session.getAttribute("name");
	String id = (String) session.getAttribute("id");
	

      out.write("\r\n");
      out.write("\t<div class=\"hd_wrap\">\r\n");
      out.write("                <a href=\"index.jsp\" class=\"logo\"><img src=\"./pic2/upbit_logo.png\" alt=\"Upbit_logo\"></a>\r\n");
      out.write("                <nav class=\"tnb\">\r\n");
      out.write("\t\t\t\t");

				if(id != null && id.equals("admin")){
				
      out.write("\t\r\n");
      out.write("                    <span class=\"name_print\">");
      out.print(name );
      out.write("님</span>\r\n");
      out.write("                    <a href=\"memList.jsp\">회원관리</a>\r\n");
      out.write("                    <a href=\"logout.jsp\">로그아웃</a>\r\n");
      out.write("                    <a href=\"join.jsp\">내정보</a>\r\n");
      out.write("                    <a href=\"sitemap.jsp\">사이트맵</a>\r\n");
      out.write("                ");
 
                }else if(name != null){
				
      out.write("\r\n");
      out.write("\t\t\t\t\t<span class=\"name_print\">");
      out.print(name );
      out.write("님</span>\r\n");
      out.write("                    <a href=\"logout.jsp\">로그아웃</a>\r\n");
      out.write("                    <a href=\"join.jsp\">내정보</a>\r\n");
      out.write("                    <a href=\"sitemap.jsp\">사이트맵</a>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("                ");

                }else{
                
      out.write("\r\n");
      out.write("                    <a href=\"login.jsp\">로그인</a>\r\n");
      out.write("                    <a href=\"term.jsp\">회원가입</a>\r\n");
      out.write("                    <a href=\"sitemap.jsp\">사이트맵</a>\r\n");
      out.write("                ");
 
                }
				
      out.write("\r\n");
      out.write("                </nav>\r\n");
      out.write("                <nav class=\"gnb\">\r\n");
      out.write("                    <ul>\r\n");
      out.write("                        <li class=\"item1\">\r\n");
      out.write("                            <a href=\"info.jsp#page1\" class=\"dp1\">회사소개</a>\r\n");
      out.write("                            <ul class=\"sub\">\r\n");
      out.write("                                <li><a href=\"info.jsp#page1\">연혁</a></li>\r\n");
      out.write("                                <li><a href=\"info.jsp#page2\">비전</a></li>\r\n");
      out.write("                                <li><a href=\"info.jsp#page3\">오시는길</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"item2\">\r\n");
      out.write("                            <a href=\"coin.jsp#page1\" class=\"dp1\">코인 동향</a>\r\n");
      out.write("                            <ul class=\"sub\">\r\n");
      out.write("                                <li><a href=\"coin.jsp#page1\">코인 시세</a></li>\r\n");
      out.write("                                <li><a href=\"coin.jsp#page2\">국내외증시</a></li>\r\n");
      out.write("                                <li><a href=\"coin.jsp#page3\">관련 기사</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"item3\">\r\n");
      out.write("                            <a href=\"nft.jsp#page1\" class=\"dp1\">NFT</a>\r\n");
      out.write("                            <ul class=\"sub\">\r\n");
      out.write("                                <li><a href=\"nft.jsp#page1\">Drops</a></li>\r\n");
      out.write("                                <li><a href=\"nft.jsp#page2\">Market Place</a></li>\r\n");
      out.write("                                <li><a href=\"nft.jsp#page3\">My NFT</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"item4\">\r\n");
      out.write("                            <a href=\"board.jsp\" class=\"dp1\">고객센터</a>\r\n");
      out.write("                            <ul class=\"sub\">\r\n");
      out.write("                                <li><a href=\"custom.jsp#page1\">공지사항</a></li>\r\n");
      out.write("                                <li><a href=\"faq.jsp\">자주하는질문</a></li>\r\n");
      out.write("                                <li><a href=\"qna.jsp\">QnA</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </nav>\r\n");
      out.write("            </div>");
      out.write("\r\n");
      out.write("        </header>\r\n");
      out.write("        <div class=\"content\" id=\"page1\">\r\n");
      out.write("            <figure class=\"vs\">\r\n");
      out.write("                <img src=\"\" alt=\"비주얼\">\r\n");
      out.write("            </figure>\r\n");
      out.write("            <div class=\"bread\">\r\n");
      out.write("                <div class=\"bread_fr\">\r\n");
      out.write("                    <a href=\"index.jsp\" class=\"home\">HOME</a> &gt;\r\n");
      out.write("                    <select name=\"sel1\" id=\"sel1\" class=\"sel\">\r\n");
      out.write("                        <option>고객센터</option>\r\n");
      out.write("                        <option value=\"info.jsp#page1\">업비트소개</option>\r\n");
      out.write("                        <option value=\"coin.jsp#page1\">동향</option>\r\n");
      out.write("                        <option value=\"nft.jsp#page1\">NFT</option>\r\n");
      out.write("                    </select> &gt;\r\n");
      out.write("                    <select name=\"sel2\" id=\"sel2\" class=\"sel\">\r\n");
      out.write("                        <option>공지사항</option>\r\n");
      out.write("                        <option value=\"custom.jsp#page2\">자주하는질문</option>\r\n");
      out.write("                        <option value=\"custom.jsp#page3\">QnA</option>\r\n");
      out.write("                    </select>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <section class=\"page\">\r\n");
      out.write("                <div class=\"page_wrap\">\r\n");
      out.write("                    <h2 class=\"page_title\">글 목록</h2>\r\n");
      out.write("                    <ul class=\"noti_lst\">\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <span class=\"noti_num item_hd\">연번</span>\r\n");
      out.write("                            <span class=\"not_tit item_hd\">제목</span>\r\n");
      out.write("                            <span class=\"noti_auth item_hd\">작성자</span>\r\n");
      out.write("                            <span class=\"noti_date item_hd\">작성일</span>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <span class=\"noti_num\">1</span>\r\n");
      out.write("                            <span class=\"not_tit\"><a href=\"\">공지사항</a></span>\r\n");
      out.write("                            <span class=\"noti_auth\">김기태</span>\r\n");
      out.write("                            <span class=\"noti_date\">2022-10-18</span>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <span class=\"noti_num\">2</span>\r\n");
      out.write("                            <span class=\"not_tit\"><a href=\"\">글 제목2</a></span>\r\n");
      out.write("                            <span class=\"noti_auth\">김기태</span>\r\n");
      out.write("                            <span class=\"noti_date\">2022-10-18</span>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li><span class=\"noti_num\">3</span><span class=\"not_tit\"><a href=\"\">글 제목3</a></span><span class=\"noti_auth\">김기태</span><span class=\"noti_date\">2022-10-18</span></li>\r\n");
      out.write("                        <li><span class=\"noti_num\">4</span><span class=\"not_tit\"><a href=\"\">글 제목4</a></span><span class=\"noti_auth\">김기태</span><span class=\"noti_date\">2022-10-18</span></li>\r\n");
      out.write("                        <li><span class=\"noti_num\">5</span><span class=\"not_tit\"><a href=\"\">글 제목5</a></span><span class=\"noti_auth\">김기태</span><span class=\"noti_date\">2022-10-18</span></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("            </section>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"content\" id=\"page2\">\r\n");
      out.write("            <figure class=\"vs\">\r\n");
      out.write("                <img src=\"\" alt=\"비주얼\">\r\n");
      out.write("            </figure>\r\n");
      out.write("            <div class=\"bread\">\r\n");
      out.write("                <div class=\"bread_fr\">\r\n");
      out.write("                    <a href=\"index.jsp\" class=\"home\">HOME</a> &gt;\r\n");
      out.write("                    <select name=\"sel3\" id=\"sel3\" class=\"sel\">\r\n");
      out.write("                        <option>고객센터</option>\r\n");
      out.write("                        <option value=\"info.jsp#page1\">업비트소개</option>\r\n");
      out.write("                        <option value=\"coin.jsp#page1\">동향</option>\r\n");
      out.write("                        <option value=\"nft.jsp#page1\">NFT</option>\r\n");
      out.write("                    </select> &gt;\r\n");
      out.write("                    <select name=\"sel4\" id=\"sel4\" class=\"sel\">\r\n");
      out.write("                        <option selected>자주하는질문</option>\r\n");
      out.write("                        <option value=\"custom.jsp#page1\">공지사항</option>\r\n");
      out.write("                        <option value=\"custom.jsp#page3\">QnA</option>\r\n");
      out.write("                    </select>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <section class=\"page\">\r\n");
      out.write("                <div class=\"page_wrap\">\r\n");
      out.write("                    <h2 class=\"page_title\">글 목록</h2>\r\n");
      out.write("                    <ul class=\"noti_lst\">\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <span class=\"noti_num item_hd\">연번</span>\r\n");
      out.write("                            <span class=\"not_tit item_hd\">제목</span>\r\n");
      out.write("                            <span class=\"noti_auth item_hd\">작성자</span>\r\n");
      out.write("                            <span class=\"noti_date item_hd\">작성일</span>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <span class=\"noti_num\">1</span>\r\n");
      out.write("                            <span class=\"not_tit\"><a href=\"\">공지사항</a></span>\r\n");
      out.write("                            <span class=\"noti_auth\">김기태</span>\r\n");
      out.write("                            <span class=\"noti_date\">2022-10-18</span>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <span class=\"noti_num\">2</span>\r\n");
      out.write("                            <span class=\"not_tit\"><a href=\"\">글 제목2</a></span>\r\n");
      out.write("                            <span class=\"noti_auth\">김기태</span>\r\n");
      out.write("                            <span class=\"noti_date\">2022-10-18</span>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li><span class=\"noti_num\">3</span><span class=\"not_tit\"><a href=\"\">글 제목3</a></span><span class=\"noti_auth\">김기태</span><span class=\"noti_date\">2022-10-18</span></li>\r\n");
      out.write("                        <li><span class=\"noti_num\">4</span><span class=\"not_tit\"><a href=\"\">글 제목4</a></span><span class=\"noti_auth\">김기태</span><span class=\"noti_date\">2022-10-18</span></li>\r\n");
      out.write("                        <li><span class=\"noti_num\">5</span><span class=\"not_tit\"><a href=\"\">글 제목5</a></span><span class=\"noti_auth\">김기태</span><span class=\"noti_date\">2022-10-18</span></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("            </section>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"content\" id=\"page3\">\r\n");
      out.write("            <figure class=\"vs\">\r\n");
      out.write("                <img src=\"img/baner/product_3.jpg\" alt=\"비주얼\">\r\n");
      out.write("            </figure>\r\n");
      out.write("            <div class=\"bread\">\r\n");
      out.write("                <div class=\"bread_fr\">\r\n");
      out.write("                    <a href=\"index.jsp\" class=\"home\">HOME</a> &gt;\r\n");
      out.write("                    <select name=\"sel5\" id=\"sel5\" class=\"sel\">\r\n");
      out.write("                        <option>고객센터</option>\r\n");
      out.write("                        <option value=\"info.jsp#page1\">업비트소개</option>\r\n");
      out.write("                        <option value=\"coin.jsp#page1\">동향</option>\r\n");
      out.write("                        <option value=\"nft.jsp#page1\">NFT</option>\r\n");
      out.write("                    </select> &gt;\r\n");
      out.write("                    <select name=\"sel6\" id=\"sel6\" class=\"sel\">\r\n");
      out.write("                        <option selected>QnA</option>\r\n");
      out.write("                        <option value=\"custom.jsp#page1\">공지사항</option>\r\n");
      out.write("                        <option value=\"custom.jsp#page2\">자주하는질문</option>\r\n");
      out.write("                    </select>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <section class=\"page\">\r\n");
      out.write("                <div class=\"page_wrap\">\r\n");
      out.write("                    <h2 class=\"page_title\">글 목록</h2>\r\n");
      out.write("                    <ul class=\"noti_lst\">\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <span class=\"noti_num item_hd\">연번</span>\r\n");
      out.write("                            <span class=\"not_tit item_hd\">제목</span>\r\n");
      out.write("                            <span class=\"noti_auth item_hd\">작성자</span>\r\n");
      out.write("                            <span class=\"noti_date item_hd\">작성일</span>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <span class=\"noti_num\">1</span>\r\n");
      out.write("                            <span class=\"not_tit\"><a href=\"\">공지사항</a></span>\r\n");
      out.write("                            <span class=\"noti_auth\">김기태</span>\r\n");
      out.write("                            <span class=\"noti_date\">2022-10-18</span>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <span class=\"noti_num\">2</span>\r\n");
      out.write("                            <span class=\"not_tit\"><a href=\"\">글 제목2</a></span>\r\n");
      out.write("                            <span class=\"noti_auth\">김기태</span>\r\n");
      out.write("                            <span class=\"noti_date\">2022-10-18</span>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li><span class=\"noti_num\">3</span><span class=\"not_tit\"><a href=\"\">글 제목3</a></span><span class=\"noti_auth\">김기태</span><span class=\"noti_date\">2022-10-18</span></li>\r\n");
      out.write("                        <li><span class=\"noti_num\">4</span><span class=\"not_tit\"><a href=\"\">글 제목4</a></span><span class=\"noti_auth\">김기태</span><span class=\"noti_date\">2022-10-18</span></li>\r\n");
      out.write("                        <li><span class=\"noti_num\">5</span><span class=\"not_tit\"><a href=\"\">글 제목5</a></span><span class=\"noti_auth\">김기태</span><span class=\"noti_date\">2022-10-18</span></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("            </section>\r\n");
      out.write("        </div>\r\n");
      out.write("        <script>\r\n");
      out.write("            var sel = document.getElementsByClassName(\"sel\");\r\n");
      out.write("            for (var i = 0; i < sel.length; i++) {\r\n");
      out.write("                sel[i].addEventListener(\"change\", function () {\r\n");
      out.write("                    location.href = this.value;\r\n");
      out.write("                });\r\n");
      out.write("            }\r\n");
      out.write("        </script>\r\n");
      out.write("        <footer class=\"ft\">\r\n");
      out.write("            <div class=\"ft_wrap\">\r\n");
      out.write("                <div class=\"ft_logo\"><img src=\"\" alt=\"하단로고\"></div>\r\n");
      out.write("                <div class=\"mid_box\">\r\n");
      out.write("                    <nav class=\"fnb\">\r\n");
      out.write("                        <a href=\"\" class=\"dpc\">개인정보처리방침</a>\r\n");
      out.write("                        <a href=\"\" class=\"dpc\">이용약관</a>\r\n");
      out.write("                        <a href=\"\">이메일무단수집거부</a>\r\n");
      out.write("                    </nav>\r\n");
      out.write("                    <p class=\"addr\">\r\n");
      out.write("                        두나무 주식회사 | 대표 | 이석우 | 사업자등록번호:119-86-54968<br>\r\n");
      out.write("                        서울시 강남구 테헤란로 4길 14, 5층 | 고객센터 | 1588-5682<br>\r\n");
      out.write("                        가상자산사업자 등록번호 2021-01 | 기사 배열 책임자 박동규 | 청소년 보호 책임자 송세정<br>\r\n");
      out.write("                        투자에 대한 모든 책임은 본인에게 있습니다. \r\n");
      out.write("                    </p>\r\n");
      out.write("                    <p class=\"copyright\">Copyright © 2017 - 2022 Dunamu Inc. All rights reserved.</p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"sel_box\">\r\n");
      out.write("                    <select name=\"sel\" id=\"sel\" class=\"sel\" onchange=\"sel_link(this)\">\r\n");
      out.write("                        <option value=\"\">고객지원</option>\r\n");
      out.write("                        <option value=\"https://upbitcare.com/\">투자자보호센터</option>\r\n");
      out.write("                        <option value=\"https://www.upbit.com/service_center/listing_guide\">거래지원 문의 및 제보</option>\r\n");
      out.write("                    </select>\r\n");
      out.write("                </div>\r\n");
      out.write("                <script>\r\n");
      out.write("                    function sel_link(sel) {\r\n");
      out.write("                        location.href = sel.value;\r\n");
      out.write("                    }\r\n");
      out.write("                </script>\r\n");
      out.write("            </div>\r\n");
      out.write("        </footer>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
