/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.23
 * Generated at: 2022-10-24 05:33:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/footer.jsp", Long.valueOf(1666588830193L));
    _jspx_dependants.put("/head.jsp", Long.valueOf(1666331980572L));
    _jspx_dependants.put("/nav.jsp", Long.valueOf(1666589278598L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>업비트 - 가장 신뢰받는 디지털 자산 거래소</title>\r\n");
      out.write("    <!-- 메타포(검색엔진에서 잘 검색되기 위해서) -->\r\n");
      out.write("    <meta property=\"og:url\" content=\"/home\">\r\n");
      out.write("    <meta property=\"og:site_name\" content=\"업비트 - 가장 신뢰받는 디지털 자산 거래소\">\r\n");
      out.write("    <meta property=\"og:title\" content=\"업비트\">\r\n");
      out.write("    <meta property=\"og:image\" content=\"https://static.upbit.com/upbit-pc/seo/upbit_facebook.png\">\r\n");
      out.write("    <meta property=\"og:image:width\" content=\"800\">\r\n");
      out.write("    <meta property=\"og:image:height\" content=\"400\">\r\n");
      out.write("    <meta property=\"og:description\" content=\"디지털 자산, 비트코인, 이더리움, 리플, 에이다, 솔라나 등 알트코인 거래.\">\r\n");
      out.write("    <meta property=\"og:locale\" content=\"ko_kr\">\r\n");
      out.write("    <meta property=\"og:type\" content=\"website\">\r\n");
      out.write("    <meta name=\"twitter:card\" content=\"summary\">\r\n");
      out.write("    <meta name=\"twitter:url\" content=\"/home\">\r\n");
      out.write("    <meta name=\"twitter:site_name\" content=\"업비트 - 가장 신뢰받는 디지털 자산 거래소\">\r\n");
      out.write("    <meta name=\"twitter:title\" content=업비트>\r\n");
      out.write("    <meta name=\"twitter:image\" content=\"https://static.upbit.com/upbit-pc/seo/upbit_facebook.png\">\r\n");
      out.write("    <meta name=\"twitter:image:width\" content=\"1200\">\r\n");
      out.write("    <meta name=\"twitter:image:height\" content=\"627\">\r\n");
      out.write("    <meta name=\"twitter:description\" content=\"디지털 자산, 비트코인, 이더리움, 리플, 에이다, 솔라나 등 알트코인 거래.\">\r\n");
      out.write("    <meta name=\"twitter:locale\" content=ko_kr>\r\n");
      out.write("    <meta name=\"twitter:type\" content=\"website\">\r\n");
      out.write("    <meta name=\"author\" content=두나무>\r\n");
      out.write("    <meta name=\"image\" content=\"https://static.upbit.com/upbit-pc/seo/upbit_facebook.png\">\r\n");
      out.write("    <!--파비콘-->\r\n");
      out.write("    <link rel=\"shortcut icon\" href=\"./pic/favicon.jpg\">\r\n");
      out.write("    <!--각종 플러그인과 설정 파일-->\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Nanum+Gothic&family=Noto+Sans+KR&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    <!-- 구형 브라우저 html5태그 인식 -->\r\n");
      out.write("    <script src=\"./js/html5shiv.js\"></script>\r\n");
      out.write("    <!-- 구형 브라우저에서 css animation 인식 -->\r\n");
      out.write("    <script src=\"./js/prefixfree.min.js\"></script>\r\n");
      out.write("    <!-- 구형 브라우저에서 미디어쿼리 인식 -->\r\n");
      out.write("    <script src=\"./js/respond.min.js\"></script>\r\n");
      out.write("    <!-- jquery 플러그인 연결 -->\r\n");
      out.write("    <script src=\"./js/jquery-1.11.1.js\"></script>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./css/reset2.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"header.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"footer.css\">");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"./css/reset2.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"header.css\">\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("/* header.css */\r\n");
      out.write("\r\n");
      out.write("/* content */\r\n");
      out.write(".content {\r\n");
      out.write("\tclear: both;\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".content:after {\r\n");
      out.write("\tcontent: \"\";\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\tclear: both;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".vs {\r\n");
      out.write("\tclear: both;\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\theight: 100vh;\r\n");
      out.write("\toverflow: hidden;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".vdo {\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\theight: auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".page {\r\n");
      out.write("\tclear: both;\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".page_wrap {\r\n");
      out.write("\twidth: 1200px;\r\n");
      out.write("\tmargin: 0 auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#page1, #page3 {\r\n");
      out.write("\tbackground-color: #ececec;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".page_tit {\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tfont-size: 32px;\r\n");
      out.write("\tpadding-top: 2em;\r\n");
      out.write("\tpadding-bottom: 2em;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".lst {\r\n");
      out.write("\tclear: both;\r\n");
      out.write("\twidth: 1200px;\r\n");
      out.write("\tpadding-bottom: 80px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".lst:after {\r\n");
      out.write("\tcontent: \"\";\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\tclear: both;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".lst li {\r\n");
      out.write("\tmargin-bottom: 40px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".lst li.left {\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\twidth: 620px;\r\n");
      out.write("\theight: 349px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".lst li.right {\r\n");
      out.write("\tfloat: right;\r\n");
      out.write("\twidth: 540px;\r\n");
      out.write("\theight: 349px;\r\n");
      out.write("\tpadding-top: 25px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".ico_lst {\r\n");
      out.write("\tclear: both;\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\toverflow: hidden;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".ico_lst li a {\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\tbackground-repeat: no-repeat;\r\n");
      out.write("\tbackground-position: 0 center;\r\n");
      out.write("\tbackground-size: auto 80%;\r\n");
      out.write("\tpadding-left: 85px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".ico_lst li a.icon1 {\r\n");
      out.write("\tbackground-image: url(\"./img/icon/ico_service_01.svg\");\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".ico_lst li a.icon2 {\r\n");
      out.write("\tbackground-image: url(\"./img/icon/ico_service_02.svg\");\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".ico_lst li a.icon3 {\r\n");
      out.write("\tbackground-image: url(\"./img/icon/ico_service_03.svg\");\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".cate_tit {\r\n");
      out.write("\tcolor: #222;\r\n");
      out.write("\tfont-size: 20px;\r\n");
      out.write("\tpadding-bottom: 0.5em;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".cate_com {\r\n");
      out.write("\tcolor: #222;\r\n");
      out.write("\tfont-size: 16px;\r\n");
      out.write("\toverflow: hidden;\r\n");
      out.write("\twhite-space: nowrap;\r\n");
      out.write("\ttext-overflow: ellipsis;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#page2 {\r\n");
      out.write("\tbackground-color: rgb(235, 230, 211);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".pic_lst {\r\n");
      out.write("\tclear: both;\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\tpadding-bottom: 120px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".pic_lst::after {\r\n");
      out.write("\tcontent: \"\";\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\tclear: both;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".pic_lst li {\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("\tmargin-bottom: 40px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".pic_lst li a {\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\twidth: 360px;\r\n");
      out.write("\tmargin-right: 40px;\r\n");
      out.write("\toverflow: hidden;\r\n");
      out.write("\theight: 300px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".pic_lst li a img {\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\twidth: 732px;\r\n");
      out.write("\tmargin-left: -120px;\r\n");
      out.write("\ttransition-duration: 0.8s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".pic_lst li a:hover img {\r\n");
      out.write("\tmargin-left: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".pic_lst li a .hv_box {\r\n");
      out.write("\twidth: 360px;\r\n");
      out.write("\theight: 300px;\r\n");
      out.write("\tcolor: #fff;\r\n");
      out.write("\topacity: 0;\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\ttop: 0;\r\n");
      out.write("\tleft: 0;\r\n");
      out.write("\tz-index: 10;\r\n");
      out.write("\ttransition-duration: 0.8s;\r\n");
      out.write("\tbackground-color: transparent;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".pic_lst li a:hover .hv_box {\r\n");
      out.write("\topacity: 1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".pic_date {\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\ttop: 30px;\r\n");
      out.write("\tleft: 30px;\r\n");
      out.write("\ttext-shadow: 0px 0px 3px red;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".pic_tit {\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\tright: 30px;\r\n");
      out.write("\tbottom: 30px;\r\n");
      out.write("\ttext-shadow: 0px 0px 3px blue;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#page3 {\r\n");
      out.write("\tbackground-repeat: no-repeat;\r\n");
      out.write("\tbackground-size: cover;\r\n");
      out.write("\tbackground-position: center center;\r\n");
      out.write("\theight: 100vh;\r\n");
      out.write("\tbackground-image: url(\"./img/bg_partners.jpg\");\r\n");
      out.write("\toverflow: hidden;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#page3 .page_wrap {\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".circle_lst {\r\n");
      out.write("\tclear: both;\r\n");
      out.write("\twidth: 5120px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".circle_lst li {\r\n");
      out.write("\twidth: 200px;\r\n");
      out.write("\theight: 200px;\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("\tborder-radius: 120px;\r\n");
      out.write("\toverflow: hidden;\r\n");
      out.write("\tbackground-color: #fff;\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\tmargin: 28px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".circle_lst.lst2 li {\r\n");
      out.write("\tfloat: right;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".circle_lst li a {\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\theight: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".circle_lst li img {\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\twidth: 250px;\r\n");
      out.write("\theight: auto;\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\ttop: 35%;\r\n");
      out.write("\tleft: -25px;\r\n");
      out.write("\tz-index: 11;\r\n");
      out.write("\tmargin-top: -28px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<!-- footer.css -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"footer.css\">\r\n");
      out.write("<script>\r\n");
      out.write("        $(document), ready(function () {\r\n");
      out.write("            $(window).scroll(function () {\r\n");
      out.write("                var ht = $(window).height();\r\n");
      out.write("                var tp = $(this).scrollTop();\r\n");
      out.write("                if (tp >= 600) {\r\n");
      out.write("                    $(\".hd\").css(\"position\", \"fixed\");\r\n");
      out.write("                } else {\r\n");
      out.write("                    $(\".hd\").css(\"position\", \"absolute\");\r\n");
      out.write("                }\r\n");
      out.write("            });\r\n");
      out.write("            $\r\n");
      out.write("            $(\"<ul class='circle_lst lst2'></ul>\").insertAfter($(\".circle_lst\"));\r\n");
      out.write("            $lst1_obj = $(\".circle_lst li\").clone();\r\n");
      out.write("            $(\".circle_lst.lst2\").append($lst2_obj);\r\n");
      out.write("        });\r\n");
      out.write("    </script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"wrap\">\r\n");
      out.write("\t\t<header class=\"hd\">\r\n");
      out.write("\t\t\t");
      out.write('\r');
      out.write('\n');

	String name = (String) session.getAttribute("name");

      out.write("\r\n");
      out.write("\t<div class=\"hd_wrap\">\r\n");
      out.write("                <a href=\"index.jsp\" class=\"logo\"><img src=\"./pic2/upbit_logo.png\" alt=\"Upbit_logo\"></a>\r\n");
      out.write("                <nav class=\"tnb\">\r\n");
      out.write("\t\t\t\t");

				if(name!=null){
				
      out.write("\t\r\n");
      out.write("                    <span class=\"name_print\">");
      out.print(name );
      out.write("님</span>\r\n");
      out.write("                    <a href=\"logout.jsp\">로그아웃</a>\r\n");
      out.write("                    <a href=\"join.jsp\">내정보</a>\r\n");
      out.write("                    <a href=\"sitemap.jsp\">사이트맵</a>\r\n");
      out.write("                ");
 
                }else {
				
      out.write("\r\n");
      out.write("\t\t\t\t\t<a href=\"login.jsp\">로그인</a>\r\n");
      out.write("                    <a href=\"term.jsp\">회원가입</a>\r\n");
      out.write("                    <a href=\"sitemap.jsp\">사이트맵</a>\r\n");
      out.write("                ");

                }
                
      out.write("\r\n");
      out.write("                </nav>\r\n");
      out.write("                <nav class=\"gnb\">\r\n");
      out.write("                    <ul>\r\n");
      out.write("                        <li class=\"item1\">\r\n");
      out.write("                            <a href=\"info.jsp#page1\" class=\"dp1\">회사소개</a>\r\n");
      out.write("                            <ul class=\"sub\">\r\n");
      out.write("                                <li><a href=\"info.jsp#page1\">연혁</a></li>\r\n");
      out.write("                                <li><a href=\"info.jsp#page2\">비전</a></li>\r\n");
      out.write("                                <li><a href=\"info.jsp#page3\">오시는길</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"item2\">\r\n");
      out.write("                            <a href=\"coin.jsp#page1\" class=\"dp1\">코인 동향</a>\r\n");
      out.write("                            <ul class=\"sub\">\r\n");
      out.write("                                <li><a href=\"coin.jsp#page1\">코인 시세</a></li>\r\n");
      out.write("                                <li><a href=\"coin.jsp#page2\">국내외증시</a></li>\r\n");
      out.write("                                <li><a href=\"coin.jsp#page3\">관련 기사</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"item3\">\r\n");
      out.write("                            <a href=\"nft.jsp#page1\" class=\"dp1\">NFT</a>\r\n");
      out.write("                            <ul class=\"sub\">\r\n");
      out.write("                                <li><a href=\"nft.jsp#page1\">Drops</a></li>\r\n");
      out.write("                                <li><a href=\"nft.jsp#page2\">Market Place</a></li>\r\n");
      out.write("                                <li><a href=\"nft.jsp#page3\">My NFT</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"item4\">\r\n");
      out.write("                            <a href=\"custom.jsp#page1\" class=\"dp1\">고객센터</a>\r\n");
      out.write("                            <ul class=\"sub\">\r\n");
      out.write("                                <li><a href=\"custom.jsp#page1\">공지사항</a></li>\r\n");
      out.write("                                <li><a href=\"custom.jsp#page2\">자주하는질문</a></li>\r\n");
      out.write("                                <li><a href=\"custom.jsp#page3\">QnA</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </nav>\r\n");
      out.write("            </div>");
      out.write("\r\n");
      out.write("\t\t</header>\r\n");
      out.write("\t\t<div class=\"content\">\r\n");
      out.write("\t\t\t<figure class=\"vs\">\r\n");
      out.write("\t\t\t\t<video src=\"./video/upbit_main.mp4\" autoplay muted loop class=\"vdo\"></video>\r\n");
      out.write("\t\t\t</figure>\r\n");
      out.write("\t\t\t<section class=\"page\" id=\"page1\">\r\n");
      out.write("\t\t\t\t<div class=\"page_wrap\">\r\n");
      out.write("\t\t\t\t\t<h2 class=\"page_tit\">\r\n");
      out.write("\t\t\t\t\t\t가장 신뢰받는 글로벌 디지털 거래소<br>안전하고 투명한 시스템으로 빠르고 편리한 거래환경을 제공합니다.\r\n");
      out.write("\t\t\t\t\t</h2>\r\n");
      out.write("\t\t\t\t\t<ul class=\"lst\">\r\n");
      out.write("\t\t\t\t\t\t<li class=\"left\"><iframe name=\"vdo2\" id=\"vdo2\" width=\"620\" height=\"349\" src=\"https://www.youtube.com/embed/4nWx3LMaUHw\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"right\">\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"ico_lst\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"https://www.youtube.com/embed/4nWx3LMaUHw\" target=\"vdo2\" class=\"icon1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h3 class=\"cate_tit\">대한민국 1등 코인거래소</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<p class=\"cate_com\">890만명이 선택한 거래소 업비트.</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"https://www.youtube.com/embed/0YTRl6RZnYo\" target=\"vdo2\" class=\"icon2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h3 class=\"cate_tit\">한 때는 코스피 거래대금 추월</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<p class=\"cate_com\">불장은 다시 옵니다!!!!!</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"https://www.youtube.com/embed/TFjI1Ea5HoE\" target=\"vdo2\" class=\"icon3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h3 class=\"cate_tit\">빠르고 편한 모바일 앱</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<p class=\"cate_com\">스마트폰으로 간편하게 거래해보세요</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</section>\r\n");
      out.write("\t\t\t<section class=\"page\" id=\"page2\">\r\n");
      out.write("\t\t\t\t<div class=\"page_wrap\">\r\n");
      out.write("\t\t\t\t\t<h2 class=\"page_tit\">\r\n");
      out.write("\t\t\t\t\t\t실시간 거래대금 Top 3<br>코인 정보\r\n");
      out.write("\t\t\t\t\t</h2>\r\n");
      out.write("\t\t\t\t\t<ul class=\"pic_lst\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"https://upbit.com/exchange?code=CRIX.UPBIT.KRW-XRP\"> <img src=\"./pic2/xrp_info.PNG\" alt=\"XRP_INFO\" class=\"pic\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"hv_box\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p class=\"pic_tit\">리플(XRP)</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"\"> <img src=\"./pic2/bitcoin_info.PNG\" alt=\"BTC_INFO\" class=\"pic\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"hv_box\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p class=\"pic_tit\">비트코인(BTC)</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"\"> <img src=\"./pic2/orbs_info.PNG\" alt=\"ORBS_INFO\" class=\"pic\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"hv_box\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p class=\"pic_tit\">오브스(ORBS)</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</section>\r\n");
      out.write("\t\t\t<section class=\"page\" id=\"page3\">\r\n");
      out.write("\t\t\t\t<div class=\"page_wrap\">\r\n");
      out.write("\t\t\t\t\t<h2 class=\"page_tit\">국제 표준 및 국내 주요 보안 인증 획득</h2>\r\n");
      out.write("\t\t\t\t\t<ul class=\"circle_lst\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"\"><img src=\"./pic/인증1.svg\" alt=\"인증로고1\" class=\"thumb\"></a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"\"><img src=\"./pic/인증2.svg\" alt=\"인증로고2\" class=\"thumb\"></a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"\"><img src=\"./pic/인증3.svg\" alt=\"인증로고3\" class=\"thumb\"></a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"\"><img src=\"./pic/인증4.svg\" alt=\"인증로고4\" class=\"thumb\"></a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</section>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<footer class=\"ft\">\r\n");
      out.write("\t\t\t");
      out.write("\r\n");
      out.write("<div class=\"ft_wrap\">\r\n");
      out.write("                <div class=\"ft_logo\"><img src=\"\" alt=\"하단로고\"></div>\r\n");
      out.write("                <div class=\"mid_box\">\r\n");
      out.write("                    <nav class=\"fnb\">\r\n");
      out.write("                        <a href=\"\" class=\"dpc\">개인정보처리방침</a>\r\n");
      out.write("                        <a href=\"\" class=\"dpc\">이용약관</a>\r\n");
      out.write("                        <a href=\"\">이메일무단수집거부</a>\r\n");
      out.write("                    </nav>\r\n");
      out.write("                    <p class=\"addr\">\r\n");
      out.write("                        두나무 주식회사 | 대표 | 이석우 | 사업자등록번호:119-86-54968<br>\r\n");
      out.write("                        서울시 강남구 테헤란로 4길 14, 5층 | 고객센터 | 1588-5682<br>\r\n");
      out.write("                        가상자산사업자 등록번호 2021-01 | 기사 배열 책임자 박동규 | 청소년 보호 책임자 송세정<br>\r\n");
      out.write("                        투자에 대한 모든 책임은 본인에게 있습니다. \r\n");
      out.write("                    </p>\r\n");
      out.write("                    <p class=\"copyright\">Copyright © 2017 - 2022 Dunamu Inc. All rights reserved.</p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"sel_box\">\r\n");
      out.write("                    <select name=\"sel\" id=\"sel\" class=\"sel\" onchange=\"sel_link(this)\">\r\n");
      out.write("                        <option value=\"\">고객지원</option>\r\n");
      out.write("                        <option value=\"https://upbitcare.com/\">투자자보호센터</option>\r\n");
      out.write("                        <option value=\"https://www.upbit.com/service_center/listing_guide\">거래지원 문의 및 제보</option>\r\n");
      out.write("                    </select>\r\n");
      out.write("                </div>\r\n");
      out.write("                <script>\r\n");
      out.write("                    function sel_link(sel) {\r\n");
      out.write("                        location.href = sel.value;\r\n");
      out.write("                    }\r\n");
      out.write("                </script>\r\n");
      out.write("            </div>");
      out.write("\r\n");
      out.write("\t\t</footer>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
