/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.23
 * Generated at: 2022-10-24 05:33:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/footer.jsp", Long.valueOf(1666588830193L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<title>업비트 - 가장 신뢰받는 디지털 자산 거래소</title>\r\n");
      out.write("<!--메타포-->\r\n");
      out.write("<meta property=\"og:url\" content=\"/home\">\r\n");
      out.write("<meta property=\"og:site_name\" content=\"업비트 - 가장 신뢰받는 디지털 자산 거래소\">\r\n");
      out.write("<meta property=\"og:title\" content=\"업비트\">\r\n");
      out.write("<meta property=\"og:image\" content=\"https://static.upbit.com/upbit-pc/seo/upbit_facebook.png\">\r\n");
      out.write("<meta property=\"og:image:width\" content=\"800\">\r\n");
      out.write("<meta property=\"og:image:height\" content=\"400\">\r\n");
      out.write("<meta property=\"og:description\" content=\"디지털 자산, 비트코인, 이더리움, 리플, 에이다, 솔라나 등 알트코인 거래.\">\r\n");
      out.write("<meta property=\"og:locale\" content=\"ko_kr\">\r\n");
      out.write("<meta property=\"og:type\" content=\"website\">\r\n");
      out.write("<!--오픈그래프-->\r\n");
      out.write("<meta name=\"twitter:card\" content=\"summary\">\r\n");
      out.write("<meta name=\"twitter:url\" content=\"/home\">\r\n");
      out.write("<meta name=\"twitter:site_name\" content=\"업비트 - 가장 신뢰받는 디지털 자산 거래소\">\r\n");
      out.write("<meta name=\"twitter:title\" content=업비트>\r\n");
      out.write("<meta name=\"twitter:image\" content=\"https://static.upbit.com/upbit-pc/seo/upbit_facebook.png\">\r\n");
      out.write("<meta name=\"twitter:image:width\" content=\"1200\">\r\n");
      out.write("<meta name=\"twitter:image:height\" content=\"627\">\r\n");
      out.write("<meta name=\"twitter:description\" content=\"디지털 자산, 비트코인, 이더리움, 리플, 에이다, 솔라나 등 알트코인 거래.\">\r\n");
      out.write("<meta name=\"twitter:locale\" content=ko_kr>\r\n");
      out.write("<meta name=\"twitter:type\" content=\"website\">\r\n");
      out.write("<meta name=\"author\" content=두나무>\r\n");
      out.write("<meta name=\"image\" content=\"https://static.upbit.com/upbit-pc/seo/upbit_facebook.png\">\r\n");
      out.write("<!--파비콘-->\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"./pic/favicon.jpg\">\r\n");
      out.write("<!--각종 플러그인과 설정 파일-->\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Nanum+Gothic&family=Noto+Sans+KR&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<!-- 구형 브라우저 html5태그 인식 -->\r\n");
      out.write("<script src=\"./js/html5shiv.js\"></script>\r\n");
      out.write("<!-- 구형 브라우저에서 css animation 인식 -->\r\n");
      out.write("<script src=\"./js/prefixfree.min.js\"></script>\r\n");
      out.write("<!-- 구형 브라우저에서 미디어쿼리 인식 -->\r\n");
      out.write("<script src=\"./js/respond.min.js\"></script>\r\n");
      out.write("<!-- jquery 플러그인 연결 -->\r\n");
      out.write("<script src=\"./js/jquery-1.11.1.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"./css/reset2.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"header.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"footer.css\">\r\n");
      out.write("<style>\r\n");
      out.write("/* header.css */\r\n");
      out.write(".hd {\r\n");
      out.write("\tposition: fixed;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* content */\r\n");
      out.write(".vs {\r\n");
      out.write("\tclear: both;\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\theight: 300px;\r\n");
      out.write("\toverflow: hidden;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".vs img {\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\theight: auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".bread {\r\n");
      out.write("\tclear: both;\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\tline-height: 60px;\r\n");
      out.write("\tborder-bottom: 3px solid #eee;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".bread_fr {\r\n");
      out.write("\twidth: 1200px;\r\n");
      out.write("\tmargin: 0 auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".page {\r\n");
      out.write("\tclear: both;\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\tmin-height: 100vh;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".page:after {\r\n");
      out.write("\tcontent: \"\";\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\tclear: both;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".page_wrap {\r\n");
      out.write("\twidth: 1200px;\r\n");
      out.write("\tmargin: 0 auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".page_title {\r\n");
      out.write("\tpadding-top: 1em;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".home {\r\n");
      out.write("\tcolor: #333;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".frm {\r\n");
      out.write("\tborder: 2px solid #333;\r\n");
      out.write("\tpadding: 24px;\r\n");
      out.write("\twidth: 580px;\r\n");
      out.write("\tmargin: 50px auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".frm_tb {\r\n");
      out.write("\tdisplay: table;\r\n");
      out.write("\tmargin: 40px auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".frm_tb tr {\r\n");
      out.write("\tdisplay: table-row;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".frm_tb td, .frm_tb th {\r\n");
      out.write("\tdisplay: table-cell;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".frm_tb th {\r\n");
      out.write("\twidth: 200px;\r\n");
      out.write("\theight: 48px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".frm_tb td {\r\n");
      out.write("\twidth: 300px;\r\n");
      out.write("\theight: 48px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".frm_tb label:before {\r\n");
      out.write("\tcontent: \"*\";\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".in_dt {\r\n");
      out.write("\tbackground-color: #fff;\r\n");
      out.write("\theight: 32px;\r\n");
      out.write("\tline-height: 32px;\r\n");
      out.write("\twidth: 280px;\r\n");
      out.write("\tcolor: #f36;\r\n");
      out.write("\tfont-size: 16px;\r\n");
      out.write("\ttext-indent: 0.5em;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".in_btn {\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\tbackground-color: #333;\r\n");
      out.write("\tmin-width: 120px;\r\n");
      out.write("\theight: 32px;\r\n");
      out.write("\tline-height: 32px;\r\n");
      out.write("\tborder-radius: 20px;\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\tmargin-left: 80px;\r\n");
      out.write("\tmargin-right: 20px;\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".in_btn:hover {\r\n");
      out.write("\tbackground-color: deepskyblue;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* ul > li 를 테이블 처럼 출력 */\r\n");
      out.write(".frm_tb {\r\n");
      out.write("\tdisplay: table;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".frm_tb li {\r\n");
      out.write("\tdisplay: table-row;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".frm_tb .td, .frm_tb .th, .frm_tb .td2 {\r\n");
      out.write("\tdisplay: table-cell;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".frm_tb .th {\r\n");
      out.write("\twidth: 200px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".frm_tb .td {\r\n");
      out.write("\twidth: 200px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".frm_tb .td2 {\r\n");
      out.write("\twidth: 400px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"footer.css\">\r\n");
      out.write("<script>\r\n");
      out.write("\t$(document).ready(function() {\r\n");
      out.write("\t\t$(\".to_top\").attr(\"href\", location.href);\r\n");
      out.write("\t\t$(window).scroll(function() {\r\n");
      out.write("\t\t\tvar ht = $(window).height();\r\n");
      out.write("\t\t\tvar tp = $(this).scrollTop();\r\n");
      out.write("\t\t\tif (tp >= 300) {\r\n");
      out.write("\t\t\t\t$(\".to_top\").addClass(\"on\");\r\n");
      out.write("\t\t\t\t$(\".to_top\").attr(\"href\", location.href);\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\t$(\".to_top\").removeClass(\"on\");\r\n");
      out.write("\t\t\t\t$(\".to_top\").attr(\"href\", location.href);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"wrap\">\r\n");
      out.write("\t\t<header class=\"hd\">\r\n");
      out.write("\t\t\t<div class=\"hd_wrap\">\r\n");
      out.write("\t\t\t\t<a href=\"index.jsp\" class=\"logo\"><img src=\"./pic2/upbit_logo.png\" alt=\"Upbit_logo\"></a>\r\n");
      out.write("\t\t\t\t<nav class=\"tnb\">\r\n");
      out.write("\t\t\t\t\t<a href=\"login.jsp\">로그인</a> <a href=\"join.jsp\">회원가입</a> <a href=\"sitemap.jsp\">사이트맵</a>\r\n");
      out.write("\t\t\t\t</nav>\r\n");
      out.write("\t\t\t\t<nav class=\"gnb\">\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"item1\"><a href=\"\" class=\"dp1\">업비트 소개</a>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"sub\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"info.jsp#page1\">비전/연혁</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"info.jsp#page2\">자회사/투자사</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"info.jsp#page3\">오시는길</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"item2\"><a href=\"\" class=\"dp1\">동향</a>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"sub\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"coin.jsp#page1\">코인 시세</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"coin.jsp#page2\">국내 증시</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"coin.jsp#page3\">해외 증시</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"item3\"><a href=\"\" class=\"dp1\">NFT</a>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"sub\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"nft.jsp#page1\">Drops</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"nft.jsp#page1\">Market Place</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"nft.jsp#page1\">My NFT</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"item4\"><a href=\"\" class=\"dp1\">고객센터</a>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"sub\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"custom.jsp#page1\">공지사항</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"custom.jsp#page2\">업비트 소식</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"custom.jsp#page3\">1:1 문의하기</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"custom.jsp#page4\">문의 내역</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t\t\t<!-- <li class=\"item5\">\r\n");
      out.write("                            <a href=\"\" class=\"dp1\">설치 사례</a>\r\n");
      out.write("                            <ul class=\"sub\">\r\n");
      out.write("                                <li><a href=\"\">기업별</a></li>\r\n");
      out.write("                                <li><a href=\"\">시설별</a></li>\r\n");
      out.write("                                <li><a href=\"\">기기별</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </li>-->\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</nav>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</header>\r\n");
      out.write("\t\t<div class=\"content\">\r\n");
      out.write("\t\t\t<figure class=\"vs\">\r\n");
      out.write("\t\t\t\t<img src=\"./img/vs1.jpg\" alt=\"비주얼\">\r\n");
      out.write("\t\t\t</figure>\r\n");
      out.write("\t\t\t<div class=\"bread\">\r\n");
      out.write("\t\t\t\t<div class=\"bread_fr\">\r\n");
      out.write("\t\t\t\t\t<a href=\"index.jsp\" class=\"home\">HOME</a> &gt; <span class=\"sel\">로그인</span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<section class=\"page\">\r\n");
      out.write("\t\t\t\t<div class=\"page_wrap\">\r\n");
      out.write("\t\t\t\t\t<h2 class=\"page_title\">로그인</h2>\r\n");
      out.write("\t\t\t\t\t<div class=\"form_fr\">\r\n");
      out.write("\t\t\t\t\t\t<form name=\"frm1\" action=\"loginPro.jsp\" method=\"post\" id=\"loginForm\" class=\"frm\">\r\n");
      out.write("\t\t\t\t\t\t\t<table class=\"frm_tb\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th><label for=\"id\">아이디</label></th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td><input type=\"text\" id=\"id\" name=\"id\" class=\"in_dt\" required autofocus></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th><label for=\"id\">비밀번호</label></th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td><input type=\"password\" id=\"pw\" name=\"pw\" class=\"in_dt\" required></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td colspan=\"2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<button type=\"submit\" class=\"in_btn\">로그인</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<button type=\"reset\" class=\"in_btn\">취소</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</section>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<footer class=\"ft\">\r\n");
      out.write("\t\t\t");
      out.write("\r\n");
      out.write("<div class=\"ft_wrap\">\r\n");
      out.write("                <div class=\"ft_logo\"><img src=\"\" alt=\"하단로고\"></div>\r\n");
      out.write("                <div class=\"mid_box\">\r\n");
      out.write("                    <nav class=\"fnb\">\r\n");
      out.write("                        <a href=\"\" class=\"dpc\">개인정보처리방침</a>\r\n");
      out.write("                        <a href=\"\" class=\"dpc\">이용약관</a>\r\n");
      out.write("                        <a href=\"\">이메일무단수집거부</a>\r\n");
      out.write("                    </nav>\r\n");
      out.write("                    <p class=\"addr\">\r\n");
      out.write("                        두나무 주식회사 | 대표 | 이석우 | 사업자등록번호:119-86-54968<br>\r\n");
      out.write("                        서울시 강남구 테헤란로 4길 14, 5층 | 고객센터 | 1588-5682<br>\r\n");
      out.write("                        가상자산사업자 등록번호 2021-01 | 기사 배열 책임자 박동규 | 청소년 보호 책임자 송세정<br>\r\n");
      out.write("                        투자에 대한 모든 책임은 본인에게 있습니다. \r\n");
      out.write("                    </p>\r\n");
      out.write("                    <p class=\"copyright\">Copyright © 2017 - 2022 Dunamu Inc. All rights reserved.</p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"sel_box\">\r\n");
      out.write("                    <select name=\"sel\" id=\"sel\" class=\"sel\" onchange=\"sel_link(this)\">\r\n");
      out.write("                        <option value=\"\">고객지원</option>\r\n");
      out.write("                        <option value=\"https://upbitcare.com/\">투자자보호센터</option>\r\n");
      out.write("                        <option value=\"https://www.upbit.com/service_center/listing_guide\">거래지원 문의 및 제보</option>\r\n");
      out.write("                    </select>\r\n");
      out.write("                </div>\r\n");
      out.write("                <script>\r\n");
      out.write("                    function sel_link(sel) {\r\n");
      out.write("                        location.href = sel.value;\r\n");
      out.write("                    }\r\n");
      out.write("                </script>\r\n");
      out.write("            </div>");
      out.write("\r\n");
      out.write("\t\t</footer>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
