/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.23
 * Generated at: 2022-10-24 08:18:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class term_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<title>업비트 - 가장 신뢰받는 디지털 자산 거래소</title>\r\n");
      out.write("<!--메타포-->\r\n");
      out.write("<meta property=\"og:url\" content=\"/home\">\r\n");
      out.write("<meta property=\"og:site_name\" content=\"업비트 - 가장 신뢰받는 디지털 자산 거래소\">\r\n");
      out.write("<meta property=\"og:title\" content=\"업비트\">\r\n");
      out.write("<meta property=\"og:image\" content=\"https://static.upbit.com/upbit-pc/seo/upbit_facebook.png\">\r\n");
      out.write("<meta property=\"og:image:width\" content=\"800\">\r\n");
      out.write("<meta property=\"og:image:height\" content=\"400\">\r\n");
      out.write("<meta property=\"og:description\" content=\"디지털 자산, 비트코인, 이더리움, 리플, 에이다, 솔라나 등 알트코인 거래.\">\r\n");
      out.write("<meta property=\"og:locale\" content=\"ko_kr\">\r\n");
      out.write("<meta property=\"og:type\" content=\"website\">\r\n");
      out.write("<!--오픈그래프-->\r\n");
      out.write("<meta name=\"twitter:card\" content=\"summary\">\r\n");
      out.write("<meta name=\"twitter:url\" content=\"/home\">\r\n");
      out.write("<meta name=\"twitter:site_name\" content=\"업비트 - 가장 신뢰받는 디지털 자산 거래소\">\r\n");
      out.write("<meta name=\"twitter:title\" content=업비트>\r\n");
      out.write("<meta name=\"twitter:image\" content=\"https://static.upbit.com/upbit-pc/seo/upbit_facebook.png\">\r\n");
      out.write("<meta name=\"twitter:image:width\" content=\"1200\">\r\n");
      out.write("<meta name=\"twitter:image:height\" content=\"627\">\r\n");
      out.write("<meta name=\"twitter:description\" content=\"디지털 자산, 비트코인, 이더리움, 리플, 에이다, 솔라나 등 알트코인 거래.\">\r\n");
      out.write("<meta name=\"twitter:locale\" content=ko_kr>\r\n");
      out.write("<meta name=\"twitter:type\" content=\"website\">\r\n");
      out.write("<meta name=\"author\" content=두나무>\r\n");
      out.write("<meta name=\"image\" content=\"https://static.upbit.com/upbit-pc/seo/upbit_facebook.png\">\r\n");
      out.write("<!--파비콘-->\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"./pic/favicon.jpg\">\r\n");
      out.write("<!--각종 플러그인과 설정 파일-->\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Nanum+Gothic&family=Noto+Sans+KR&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<!-- 구형 브라우저 html5태그 인식 -->\r\n");
      out.write("<script src=\"./js/html5shiv.js\"></script>\r\n");
      out.write("<!-- 구형 브라우저에서 css animation 인식 -->\r\n");
      out.write("<script src=\"./js/prefixfree.min.js\"></script>\r\n");
      out.write("<!-- 구형 브라우저에서 미디어쿼리 인식 -->\r\n");
      out.write("<script src=\"./js/respond.min.js\"></script>\r\n");
      out.write("<!-- jquery 플러그인 연결 -->\r\n");
      out.write("<script src=\"./js/jquery-1.11.1.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"./css/reset2.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"header.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"footer.css\">\r\n");
      out.write("<style>\r\n");
      out.write("/* header.css */\r\n");
      out.write("\r\n");
      out.write("/* content */\r\n");
      out.write(".page {\r\n");
      out.write("\tclear: both;\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".page_wrap {\r\n");
      out.write("\twidth: 1200px;\r\n");
      out.write("\tmargin: 0 auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#page1, #page3 {\r\n");
      out.write("\tbackground-color: #ececec;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".page_tit {\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tfont-size: 32px;\r\n");
      out.write("\tpadding-top: 1.2em;\r\n");
      out.write("\tpadding-bottom: 0.8em;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".lst {\r\n");
      out.write("\tclear: both;\r\n");
      out.write("\twidth: 1200px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".lst:after {\r\n");
      out.write("\tcontent: \"\";\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\tclear: both;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".lst li {\r\n");
      out.write("\tmargin-bottom: 40px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".lst li.left {\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\twidth: 816px;\r\n");
      out.write("\theight: 459px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".lst li.right {\r\n");
      out.write("\tfloat: right;\r\n");
      out.write("\twidth: 350px;\r\n");
      out.write("\theight: 459px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".ico_lst {\r\n");
      out.write("\tclear: both;\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\toverflow: hidden;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".ico_lst li a {\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\tbackground-repeat: no-repeat;\r\n");
      out.write("\tbackground-position: 0px center;\r\n");
      out.write("\tbackground-size: auto 80%;\r\n");
      out.write("\tpadding-left: 55px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".ico_lst li a.icon1 {\r\n");
      out.write("\tbackground-image: url(\"./img/icon/ico_service_01.svg\");\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".ico_lst li a.icon2 {\r\n");
      out.write("\tbackground-image: url(\"./img/icon/ico_service_02.svg\");\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".ico_lst li a.icon3 {\r\n");
      out.write("\tbackground-image: url(\"./img/icon/ico_service_03.svg\");\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".cate_tit {\r\n");
      out.write("\tcolor: #222;\r\n");
      out.write("\tfont-size: 20px;\r\n");
      out.write("\tpadding-bottom: 0.5em;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".cate_com {\r\n");
      out.write("\tcolor: #222;\r\n");
      out.write("\tfont-size: 14px;\r\n");
      out.write("\toverflow: hidden;\r\n");
      out.write("\twhite-space: nowrap;\r\n");
      out.write("\ttext-overflow: ellipsis;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#page2 {\r\n");
      out.write("\tbackground-color: rgba(230, 248, 255, 0.5);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".pic_lst {\r\n");
      out.write("\tclear: both;\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\tpadding-bottom: 80px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".pic_lst:after {\r\n");
      out.write("\tcontent: \"\";\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\tclear: both;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".pic_lst li {\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("\tmargin-bottom: 40px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".pic_lst li a {\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\twidth: 360px;\r\n");
      out.write("\tmargin-right: 40px;\r\n");
      out.write("\toverflow: hidden;\r\n");
      out.write("\theight: 300px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".pic_lst li a img {\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\twidth: 600px;\r\n");
      out.write("\tmargin-left: -120px;\r\n");
      out.write("\ttransition-duration: 0.8s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".pic_lst li a:hover img {\r\n");
      out.write("\tmargin-left: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".pic_lst li a .hv_box {\r\n");
      out.write("\twidth: 360px;\r\n");
      out.write("\theight: 300px;\r\n");
      out.write("\tcolor: rgb(0, 26, 255);\r\n");
      out.write("\topacity: 0;\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\ttop: 0;\r\n");
      out.write("\tleft: 0;\r\n");
      out.write("\tz-index: 10;\r\n");
      out.write("\ttransition-duration: 0.8s;\r\n");
      out.write("\tbackground-color: transparent;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".pic_lst li a:hover .hv_box {\r\n");
      out.write("\topacity: 1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".pic_tit {\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\ttop: 30px;\r\n");
      out.write("\tleft: 30px;\r\n");
      out.write("\ttext-shadow: 0px 0px 7px rgba(2, 2, 3, 0.925);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".pic_com {\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\tright: 30px;\r\n");
      out.write("\tbottom: 30px;\r\n");
      out.write("\ttext-shadow: 0px 0px 7px rgba(7, 7, 10, 0.904);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#page3 {\r\n");
      out.write("\tbackground-repeat: no-repeat;\r\n");
      out.write("\tbackground-size: cover;\r\n");
      out.write("\tbackground-position: center center;\r\n");
      out.write("\theight: 100vh;\r\n");
      out.write("\tbackground-image: url(\"./img/bg_partners.jpg\");\r\n");
      out.write("\toverflow: hidden;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#page3 .page_wrap {\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".circle_lst {\r\n");
      out.write("\tclear: both;\r\n");
      out.write("\twidth: 4455px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".circle_lst li {\r\n");
      out.write("\twidth: 300px;\r\n");
      out.write("\theight: 300px;\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("\tborder-radius: 120px;\r\n");
      out.write("\toverflow: hidden;\r\n");
      out.write("\tbackground-color: #fff;\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\tmargin: 70px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".circle_lst.lst2 li {\r\n");
      out.write("\tfloat: right;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".circle_lst li a {\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\theight: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".circle_lst li a img {\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\twidth: 160px;\r\n");
      out.write("\theight: auto;\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\ttop: 45%;\r\n");
      out.write("\tleft: 60px;\r\n");
      out.write("\tz-index: 11;\r\n");
      out.write("\tmargin-top: -30px;\r\n");
      out.write("}\r\n");
      out.write("/* 약관 */\r\n");
      out.write(".agree_fr {\r\n");
      out.write("\twidth: 900px;\r\n");
      out.write("\twhite-space: pre-wrap;\r\n");
      out.write("\tmargin: 10px auto;\r\n");
      out.write("\tpadding: 24px;\r\n");
      out.write("\tborder: 2px solid #eee;\r\n");
      out.write("\theight: 600px;\r\n");
      out.write("\toverflow-y: auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn_fr {\r\n");
      out.write("\twidth: 900px;\r\n");
      out.write("\tmargin: 30px auto;\r\n");
      out.write("\tpadding: 24px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".in_btn {\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\tbackground-color: #333;\r\n");
      out.write("\tmin-width: 120px;\r\n");
      out.write("\theight: 32px;\r\n");
      out.write("\tline-height: 32px;\r\n");
      out.write("\tborder-radius: 20px;\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\tmargin-left: 80px;\r\n");
      out.write("\tmargin-right: 20px;\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".in_btn:hover {\r\n");
      out.write("\tbackground-color: deepskyblue;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"wrap\">\r\n");
      out.write("\t\t<header class=\"hd\">\r\n");
      out.write("\t\t\t<div class=\"hd_wrap\">\r\n");
      out.write("\t\t\t\t<a href=\"index.jsp\" class=\"logo\"><img src=\"./pic2/upbit_logo.png\" alt=\"Upbit_logo\"></a>\r\n");
      out.write("\t\t\t\t<nav class=\"tnb\">\r\n");
      out.write("\t\t\t\t\t<a href=\"login.jsp\">로그인</a> <a href=\"join.jsp\">회원가입</a> <a href=\"sitemap.jsp\">사이트맵</a>\r\n");
      out.write("\t\t\t\t</nav>\r\n");
      out.write("\t\t\t\t<nav class=\"gnb\">\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"item1\"><a href=\"\" class=\"dp1\">업비트 소개</a>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"sub\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"info.jsp#page1\">비전/연혁</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"info.jsp#page2\">자회사/투자사</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"info.jsp#page3\">오시는길</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"item2\"><a href=\"\" class=\"dp1\">동향</a>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"sub\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"coin.jsp#page1\">코인 시세</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"coin.jsp#page2\">국내 증시</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"coin.jsp#page3\">해외 증시</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"item3\"><a href=\"\" class=\"dp1\">NFT</a>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"sub\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"nft.jsp#page1\">Drops</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"nft.jsp#page1\">Market Place</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"nft.jsp#page1\">My NFT</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"item4\"><a href=\"\" class=\"dp1\">고객센터</a>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"sub\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"custom.jsp#page1\">공지사항</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"custom.jsp#page2\">업비트 소식</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"custom.jsp#page3\">1:1 문의하기</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"custom.jsp#page4\">문의 내역</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t\t\t<!-- <li class=\"item5\">\r\n");
      out.write("                            <a href=\"\" class=\"dp1\">설치 사례</a>\r\n");
      out.write("                            <ul class=\"sub\">\r\n");
      out.write("                                <li><a href=\"\">기업별</a></li>\r\n");
      out.write("                                <li><a href=\"\">시설별</a></li>\r\n");
      out.write("                                <li><a href=\"\">기기별</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </li>-->\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</nav>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</header>\r\n");
      out.write("\t\t<div class=\"content\">\r\n");
      out.write("\t\t\t<figure class=\"vs\">\r\n");
      out.write("\t\t\t\t<img src=\"./img/vs1.jpg\" alt=\"비주얼\">\r\n");
      out.write("\t\t\t</figure>\r\n");
      out.write("\t\t\t<div class=\"bread\">\r\n");
      out.write("\t\t\t\t<div class=\"bread_fr\">\r\n");
      out.write("\t\t\t\t\t<a href=\"index.jsp\" class=\"home\">HOME</a> &gt; <span class=\"sel\">회원 약관</span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<section class=\"page\">\r\n");
      out.write("\t\t\t\t<div class=\"page_wrap\">\r\n");
      out.write("\t\t\t\t\t<h2 class=\"page_title\">회원 약관</h2>\r\n");
      out.write("\t\t\t\t\t<div class=\"agree_fr\">\r\n");
      out.write("\t\t\t\t\t\t<dd>\r\n");
      out.write("\t\t\t\t\t\t\t제1조(개인정보의 처리목적)<br> 회사는 다음의 목적을 위해 이용자 개인정보를 처리합니다. <br> 처리하고 있는 개인정보는 다음의 목적 이외의 용도로는 이용되지 않으며,<br> 이용 목적이 변경되는 경우에는 개인정보 보호법 제18조에 따라 <br> 별도의 동의를 받는 등 필요한 조치를 이행할 예정입니다.<br>\r\n");
      out.write("\t\t\t\t\t\t</dd>\r\n");
      out.write("\t\t\t\t\t\t1. 회원가입 및 관리 - 이용자 식별, 고객확인, 이용자 정보 관리, 각종 고지사항 전달 - 비대면 본인 인증을 통한 탈퇴 처리, 휴대폰 번호 및 출금계좌 초기화 등<br> 2. 재화 또는 서비스 제공 - 디지털 자산 거래 관계 확인 - 상속 및 양도 - 디지털 자산 거래 관계의 설정·유지·해지 등 서비스 관리 전반에 관한 사항 등<br> 3. 이벤트 정보 안내 - 각종 이벤트 및 광고성 정보 제공 - 신규 서비스 및 맞춤형 서비스 제공 등<br> 4. 고충 처리 - 민원인의 신원 및 민원사항 확인 - 사실조사를 위한 연락∙통지, 처리결과 통보 - 피해구제 및 착오전송 등 ....<br>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"btn_fr\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"checkbox\" id=\"ck_item1\" name=\"ck_item\"> <label for=\"ck_item1\">약관에 동의</label><br>\r\n");
      out.write("\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" id=\"in_btn1\" class=\"in_btn\">다음 단계</button>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<script>\r\n");
      out.write("                    var in_btn1 = document.getElementById(\"in_btn1\");\r\n");
      out.write("                    var ck_item1 = document.getElementById(\"ck_item1\");\r\n");
      out.write("                    in_btn1.addEventListener(\"click\", function(){\r\n");
      out.write("                        if(ck_item1.checked) {\r\n");
      out.write("                            location.href = \"join.jsp\";\r\n");
      out.write("                        } else {\r\n");
      out.write("                            alert(\"약관에 동의하지 않으셨습니다.\");\r\n");
      out.write("                            return;\r\n");
      out.write("                        }\r\n");
      out.write("                    });    \r\n");
      out.write("                    </script>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</section>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<footer class=\"ft\">\r\n");
      out.write("\t\t\t<div class=\"ft_wrap\">\r\n");
      out.write("\t\t\t\t<div class=\"ft_logo\">\r\n");
      out.write("\t\t\t\t\t<img src=\"\" alt=\"\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"mid_box\">\r\n");
      out.write("\t\t\t\t\t<nav class=\"fnb\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"\">개인정보 처리 방침</a> <a href=\"\">이용약관</a> <a href=\"\">이메일무단수집거부</a>\r\n");
      out.write("\t\t\t\t\t</nav>\r\n");
      out.write("\t\t\t\t\t<p class=\"addr\">\r\n");
      out.write("\t\t\t\t\t\t두나무 주식회사 | 대표 | 이석우 | 사업자등록번호:119-86-54968<br> 서울시 강남구 테헤란로 4길 14, 5층 | 고객센터 | 1588-5682<br> 가상자산사업자 등록번호 2021-01 | 기사 배열 책임자 박동규 | 청소년 보호 책임자 송세정<br> 투자에 대한 모든 책임은 본인에게 있습니다.\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t<p class=\"copyright\">Copyright © 2017 - 2022 Dunamu Inc. All rights reserved.</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"sel_box\">\r\n");
      out.write("\t\t\t\t\t<select name=\"sel\" id=\"sel\" class=\"sel\" onchange=\"sel_link(this)\">\r\n");
      out.write("\t\t\t\t\t\t<option value=\"\">고객지원</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"https://upbitcare.com/\">투자자보호센터</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"https://www.upbit.com/service_center/listing_guide\">거래지원 문의 및 제보</option>\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<script>\r\n");
      out.write("                function sel_link(sel){\r\n");
      out.write("                    location.href = sel.value;\r\n");
      out.write("                }\r\n");
      out.write("                </script>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</footer>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
